### ISSUE TITLE
Possible updates required in patterns.json

### ISSUE THREAD

**Issue by xoolive** [xoolive/rs1090#3]
Some counterintuitive examples to investigate:

- aircraft `4d24ca` / `9H-VVI` (among many others): registered in Malta, out of the Malta range (`4d2000` to `4d23ff`).  
  _Does the range need to be edited?_
- aircraft `c95000` / `4W-AAL`: registered in Timor-Leste, undocumented range (Vanuatu stops at `c903ff`)
  _Does Timor-Leste have a range?_
- aircraft registrations in `T2-` are assigned to Tuvalu, no range in the `patterns.json` file. I have two occurrences `T2-6965` (`7d007c`) and `T2-6322` (`7cd518`), in the Australia range (`7c0000` to `7fffff`), mostly visible in Australia.
  _What to think?_

@espinielli any hint?

**Comment by espinielli** [comment]
ICAO docs only say for example for Malta
![image](https://github.com/xoolive/rs1090/assets/891692/2d87110c-6df2-417e-a736-b4bdec686012)

**Comment by espinielli** [comment]
Addresses are allocated (to my knowledge) in Annex 10 Volume III.
From ICAO page [1], the last Amendment of volume 3 is from 2021...

Are the examples above correct ones, or errors?

[1] https://store.icao.int/en/annexes/annex-10

**Comment by espinielli** [comment]
For 9H-VVI you can see it is in the list of the registered aircraft in Malta [2]...unfortunately they do not provide ICAO 24-bit addresses.
It is also possible that they are using a temporary address...this can be done for one year and eventually renewable...
Is this the only instance of a Maltese address beyond the allocated block?

For the others it is all reverse engineering, I guess.

[2] https://www.transport.gov.mt/aviation/aircraft-flight-standards/registration-of-aircraft-2663

**Comment by xoolive** [comment]
No I see many aircraft beyond the upper limit, with tail numbers associated to Malta.
I wonder how much reverse engineering is really necessary here... :sob:

**Comment by espinielli** [comment]
Others are using the default ranges
https://github.com/Mictronics/readsb-protobuf/blob/dev/webapp/src/script/readsb/backend/flags.ts

**Comment by xoolive** [comment]
Well similar to my file here...
