### ISSUE TITLE
Source scheme

### ISSUE THREAD

**Issue by emctoo** [xoolive/rs1090#47]
I'd like to propose a scheme for sources. Use this issue to cooperate different ideas.

Currently, it follows `[host:]port[@reference]`. The followings are valid, according to the test cases:

- rtlsdr
- rtlsdr@LFBO
- 4003
- 4003@LFBO
- 1.2.3.4:4003@LFBO

We can use the [URL standard](https://url.spec.whatwg.org/), which has a great Rust implementation [url](https://github.com/servo/rust-url). 

The scheme is `scheme://[host][:port]/[name][@reference]`.

- `scheme` is required
- both `host` and `port` could be omitted when `scheme` is `rtlsdr`.

And we get the following corresponding examples:

- rtlsdr://
- rtlsdr:///@LFBO
- tcp://:4003 or udp://:4003
- tcp://:4003/@LFBO or udp://:4003/@LFBO
- tcp://1.2.3.4:4003/@LFBO or udp://1.2.3.4:4003/@LFBO
- ws://1.2.3.4:4003/my-name@LFBO

@xoolive Looking forward to you ideas.

**Comment by xoolive** [comment]
Thanks, just thinking aloud comments...

I will try to check if we can use the url parser and fall back to the current parser. I like the url idea.

In terms of structure we have
```
- scheme: RtlSdr | TCP | UDP | Websocket  # maybe add | TCP_or_UDP 
- host
- port
- reference
```

I think it would be nice to have a parser which can keep at least some of the previous patterns valid:

- `rtlsdr` as an alias for `rtlsdr://`
- `rtlsdr@AAAA` as an alias for `rtlsdr://@AAAA`
- `:1234` as an alias for `tcp_or_udp://:1234`  
  (this means the scheme would be an Enum which also includes `TCP_or_UDP`)
- I don't have any objection for deprecating `1234` which could also be an alias for `:1234`

I will try to implement a parser based on the [rust-url](https://github.com/servo/rust-url) crate and see if this is viable.

**Comment by emctoo** [comment]
@xoolive I almost have a working one based on `rust-url`. But just try it yourself and you may have some better ideas.

Just one case, `rtlsdr@AAAA` => `rtlsdr:///@AAAA`. The `/@AAAA` is treated as the first segment of the path.

**Comment by emctoo** [comment]
I pushed my code as a PR draft. So you can check my ideas. 

Sadly the code may not work as I can't have tcp/udp server or client locally to test them for this moment.
